language: node_js
node_js:
- '8'
cache: yarn
env:
  global:
  - secure: cnowZfqaCguu++nBrqC611LXWFzsTWDwXBRs5iHQiAkHIsD+dXkeUb7kwd7ScBEllhQA8jmnskN/lOHuwF4vQU8Ae1pgvt+d1yGRtm9vjPgiL5OyXfgcPjnkeKSYvP785N9M1X8c2n6vfTroBAfExKmDzwpE7uAF3HmUzyhQf5g3Dd6JizCLmEs9jKmmfSO3QJO6v9Xjx7W+Uf7FZvlfwBlvG+5dWN8ENAqui+jmf0iOfOLVCdEW4/VY6fuPXPYkDvUVYWURPcXKyYQL21I1x9r4pKx2DTP3EuBDM7vrKUekEiwok0i6gMfH7TJEs8LVfLEB5CBrAx76w/a9k/M3h1glNk9Xsx2eDhiD0iBbb8cXfM765ZNQ9HOCk2oLD9DB9Rh2mapmbLgEls+APPnV5buh81zGBg9EM6px3U1M2BUcIAc4srh8mUHxRDgQ7eoG13hMXACaCymS+pVuYIIIYrGZrGsv0OSqtNIZ/xNHvmds6F+tnNUGg/oI9ZXRPAJIStFCKsLblEg4U+Dq5KSSSXvDiWIyNJw004nkDtp7SfEmVAEtbvNLgzfIjbyOKlMxz3nYcW4WbjrL/Ae6hgQCAt82QtC1RKW1o/TaNCsVVA+dS9S9R0rcSQZp68MEKogyXWMYOY/yfwTyX/PGI6W7umLsOd5LzD0cuwAWWhbq1B0=
  - secure: QbFiL7NuvP+MQ+H33xUYnMe1CETTOJGfHceFMWYY176+De0UZZ8+MoB0ID8cArBB/mgd3u5jUgdSBttERed0u5rG/YgFAe8wzqlqS7XjCW82HB93JFai4tivbRT7TSd9ibUreGZIHfARpQOnqjyy2B/Zc9bbZgflnUNdue9gqK8EpPu01reKSrCtxYkpLBBmsgvtAFIHdmOMYWD+2IbgfbTy4oJQL6hW/p6rEaNiEEd8lamrm3snM/eCeaOZHa4DBBJcxBQOCL0I/t9NNVoaz4AcbjRpTjyrYqTaucrmrz4hjWoLrHeg4BwmSvKJW+sGrpfoW7ntfaxZ0it8bvvTd364NatjDGMPYSmQQ0qHX0A2C/h7nUSQ3A8CXat84TFepDU7AfL8wgMIAN4Wr+mMSCo7WcGxCSsDq1yEmmnHzfYfLSfHy5VUdXeGix4hlp42LmgOFtOVRhapWCCwOT0Pw+g4St8/ifJdWsboVsmhJPid/pm5sl5FoWLgZMGmdLzHtMNGLJAME1ETEyl4prSQ0Z6PPK8JfXIj4BnHJ/9aBud2vkhuvMdyuQ0MUuxW/TeLGQw5AaVNaAmO78JAl17WoBazIxgMnAuNvSVIKkAdydsj/KFcE238yvMGzDPPis9Ak85CC7x/tKjnTn4nW86k+QphLLoL1rWf4almXEZHNEo=
addons:
  chrome: stable
before_install:
- yarn global add lerna
install:
- lerna bootstrap
- yarn install --cwd packages/hex-react/example
jobs:
  include:
  - stage: build
    script:
    - lerna run build
  - stage: test
    script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:ci
  - script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:a11y
  - script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:integration
