language: node_js
node_js:
- '8'
cache: yarn
sudo: required
env:
  global:
  - secure: Ps+78YA3bkD5pCWEUn9V1V88OG0rkN4ZRldF7QUyPPh53G2ygHT8YuDBW5QprNeypfHW6U+MQo8eI/7jsuIlHspPjZhva9qQ+dVwSEy7a5oQ0yj7MIGiQ+jips3PaLq6IfTY1P6rDK9FjFn7LmNPAoS4sDRQsyGaRtyjrAFm28m0FmYUXgHajr/U7GqMu45xndgh/3Vai3aM0EdiuYAUAwQKDPqORpsLGN3OrbCyWUUGKWc7b50rES8NfgGcVj/MTUzY+BOhHscvl6RpmGZKNF0A22vg3MWx0Rgn8IRBouXYwF/r888l/utq65gyGKWzK85/ClUpCn0DhGjJKchDY+0vc/lz+v6a6q1R9x32ltYKRFkpLbAU31nkupPvSdslxJfCxxcWGRYLQi9zw4oWUK5qouNRs19jOKQ0KJZpPp7lm0b5aZ2DHw0wg7hneUTWto1zRJ68ceAMyB8fQIDMSLK5Htg/rXjZu0b6Xs66/ciDd097wxOoTn3IHolT5PL7bs+47Mezwo9LjNEXEF5jMUIK3C/zLV+VLbSfbL+a0RJ/qBSPUv24uPSDvEvshiK2BX0IxK6XTnbJc0nAwxhVy1juPekNnNoaFBlK3JYXylRz25jE8USLZcER02anKHHut61TUV+jSqUc57Hy37O2TDEhls/2Y20kedIEGJLM18o=
  - secure: TPJRQIohc8qMVIuJkkyk/5oy0W0DljVh9SX+4RkOCD4VVrCg9qF/T4nyv4Ks8+nR8wE4RtU6OaWOa6RpJvJpfXZNF2KhCfwtD71NoC9BFcZ8H3sJOJXzpG8rSacw34kddnop4+zOtmLV7S84vo/ic+kTIIid61U1jioTmz4i8EQP1kOpci2798n77rXYivv+eH2+kecpp8O18VS6YHFb/1HQrS5Lh+B5ejlLfHmG9wjlSgI0csc+K2MeC2GYa1gtG4wn/jF31JYMEqZjHNhHkv4K6nFM3mvkCfLrY1J32vkj4zqLyYgF70GzwKdZO4GECJ6zKAWLtHUQC+bzkzpZpFAdab7nLLhbaufj3WfmLdQ1NSc1S1cVOj/MuT33ToQtW6ARpZI0JrFHJVg/KYO0rfrSzRwaGLUUrgOpPcCvv8itNwyYFoqYRzW/UP0UW5WZgRXvAN+dbQosBgmb0mnffpwS2I5teyS6pBn8fV0eeXj1mpYxG9hzk4+AsmhmIwKB+IGDZaIYX389edEp5lE3oOyFVsl8+04BZINUC8Dvm47Aqe404Mh1MSIBRWCRzl+CS5+eW1yBvhsS0JY0laiVSaoxQQecql827wy4Uti6zK0dvVO/ZDtkQxVP5tJhEt3aMbW3cHb1d2yPB80e42p3oXKFMZKkt3yxtQtX7T0OtLI=
addons:
  chrome: stable
before_install:
- echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
- yarn global add lerna
install:
- lerna bootstrap
- yarn install --cwd packages/hex-react/example
jobs:
  include:
  - stage: build
    script:
    - lerna run build
  - stage: test
    script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:ci
  - script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:a11y
  - script:
    - lerna run --scope @bitnami/hex-react build
    - lerna run --scope @bitnami/hex-react build:dev
    - lerna run --scope @bitnami/hex-react test:integration
