language: node_js
node_js:
  - "8"
cache: yarn
addons:
  chrome: stable
before_install:
  - yarn global add lerna
install:
  - lerna bootstrap

jobs:
  include:
    - stage: build
      script:
        - lerna run build
    - stage: test
      script:
        - yarn install --cwd packages/hex-react/example
        - lerna run --scope @bitnami/hex-react build
        - lerna run --scope @bitnami/hex-react build:dev
        - lerna run --scope @bitnami/hex-react test:ci
        - lerna run --scope @bitnami/hex-react test:a11y
