language: node_js
node_js:
  - "8"
cache: yarn
before_install:
  - yarn global add lerna
install:
  - lerna bootstrap

jobs:
  include:
    - stage: build
      script:
        - lerna run --scope @bitnami/hex build
        - lerna run --scope @bitnami/hex-core build
        - lerna run --scope @bitnami/hex-js build
        - lerna run --scope @bitnami/hex-docs build
