version: '2'

services:
  hex:
    build: .
    image: hex
    ports:
      - 8080:8080
    volumes:
      - .:/app
    tty: true
    entrypoint: /app/scripts/entrypoint.sh
    command: yarn run docs
    environment:
      HEX_ENV: development
      VIRTUAL_HOST: hex-dev.docker
      VIRTUAL_PORT: 8080
