version: '2'

services:
  bitnami-ui:
    build: .
    image: bitnami-ui-dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    entrypoint: /app/scripts/entrypoint.sh
    command: npm run docs:serve
    environment:
      VIRTUAL_HOST: bitnami-ui-dev.docker
      VIRTUAL_PORT: 8080
