# The directory containing the source files to parse recursively
source:
  - ../foundations/**/*.scss
  - ../foundations/**/*.md
  - ../components/**/*.scss
  - ../components/**/*.md

source_type:
  - .css
  - .sass
  - .scss
  - .styl

# The directory that aigis will build to
dest: ./dist

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./assets
  - ../dist/bitnami.ui.css
  - ../dist/bitnami.ui.min.css
  - ../dist/bitnami.ui.components.css
  - ../dist/bitnami.ui.components.min.css
  - ../dist/bitnami.ui.js
  - ../dist/bitnami.ui.min.js

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./templates
template_engine: ejs

helper_options:
  disable_link_index: false

preview_class: Component__Preview

# For debugging purposes
log: false
